---
- name: "Add nvidia-docker repo"
  ansible.builtin.shell: yum-config-manager --add-repo https://nvidia.github.io/nvidia-docker/amzn2/nvidia-docker.repo
  args:
    creates: /etc/yum.repos.d/nvidia-docker.repo
  notify: yum-clean-metadata

- name: install packages
  yum:
    name:
      - nvidia-container-toolkit
      - nvidia-docker2
    state: present
    update_cache: yes
  notify: restart docker

- name: "Flush handlers"
  meta: flush_handlers