---
- name: "Check dependencies"
  block:
  - name: Install kernel packages for current version
    yum:
      name:
        - kernel-headers-{{ ansible_kernel }}
        - kernel-devel-{{ ansible_kernel }}
      state: present
  rescue:
  - name: Update to latest supported version
    yum:
      name:
        - kernel-devel
        - kernel-headers
      state: latest
  - name: reboot to pick up the new kernel
    notify: system-reboot

- name: "Install additional dependencies"
  ansible.builtin.yum:
    name:
      - gcc10
      - kernel-devel
      - kernel-headers
      - dkms
    state: present

- name: blacklist nouveau
  kernel_blacklist:
    name: nouveau
    state: present

- name: "Download the NVidia Installer"
  ansible.builtin.get_url:
    url: "https://us.download.nvidia.com/tesla/{{ nvidia_driver_version }}/NVIDIA-Linux-x86_64-{{ nvidia_driver_version }}.run"
    dest: "/tmp/nvidia-installer.run"
    mode: '0755'
  
- name: "Install NVidia drivers"
  ansible.builtin.shell: "sudo CC=gcc10-cc sh /tmp/nvidia-installer.run -q -a --ui=none"

- name: enable persistenced
  systemd:
    name: nvidia-persistenced
    enabled: yes

- name: "Flush handlers"
  meta: flush_handlers
