{
 "title": "AWS EFA",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(node_amazonefa_info, instance)"
    }
   },
   {
    "name": "device",
    "query": {
     "query": "label_values(node_amazonefa_info, device)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "EFA Transmitted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(node_amazonefa_tx_bytes{device=~\"${device}\", instance=~\"${instance}\"}[1m])",
     "legendFormat": "{{instance}} - {{device}}"
    }
   ]
  },
  {
   "title": "EFA Number of packets transmitted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(node_amazonefa_tx_pkts{device=~\"${device}\", instance=~\"${instance}\"}[1m])",
     "legendFormat": "{{instance}} - {{device}}"
    }
   ]
  },
  {
   "title": "RDMA read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(node_amazonefa_rdma_read_bytes{device=~\"${device}\", instance=~\"${instance}\"}[1m])",
     "legendFormat": "{{instance}} - {{device}}"
    }
   ]
  },
  {
   "title": "NVIDIA - NVlink BW total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_NVLINK_BANDWIDTH_TOTAL",
     "legendFormat": "{{instance}} - {{device}}"
    }
   ]
  },
  {
   "title": "GPU utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    { "expr": "DCGM_FI_DEV_GPU_UTIL" }
   ]
  }
 ]
}