---
- name: "Install docker"
  ansible.builtin.shell: amazon-linux-extras install docker

- name: "Enable docker"
  ansible.builtin.systemd:
    name: docker.service
    enabled: true
  notify: restart docker

- name: "Add remote user to docker group for non-privileged users to run docker"
  user:
    name: "{{ username }}"
    group: "docker"
    append: yes

- name: "Flush handlers"
  meta: flush_handlers
