---
- name: "Set sysctl values"
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    sysctl_set: true
  loop: "{{ base_sysctl | dict2items }}"


# - name: Passwordless SSH
#   ansible.builtin.blockinfile:
#     path: /etc/ssh/ssh_config
#     block: |
#         StrictHostKeyChecking no
#         HostbasedAuthentication no
#         CheckHostIP no
